package com.bilgidoku.rom.cokluortam;

public class Categories {
	public final static String[] representative = new String[] { "Landscapes.City", "Landscapes.Village",
			"Landscapes.Countryside", "Landscapes.Mountain", "Landscapes.Island", "Landscapes.Desert",
			"Landscapes.Water", "Landscapes.Sky", "Landscapes.Underwater", "Landscapes.Natural Landscape",
			"Landscapes.Natural Disasters", "Landscapes.Bird's Eye View", "Landscapes.Other",
			"Architecture.Historical Architecture", "Architecture.Statues/Creations", "Architecture.Religious/Sacred",
			"Architecture.Modern Building", "Architecture.Industrial", "Architecture.Commercial Building ",
			"Architecture.Home Renovations", "Architecture.Public Construction", "Architecture.Monuments",
			"Architecture.Infrastructure", "Architecture.Other", "People.In Studio", "People.On Location",
			"People.In Action", "People.Body Part", "People.In Uniform", "Fauna & Flora.Animals",
			"Fauna & Flora.Flora", "Objects.Art", "Objects.Health/Hygiene", "Objects.Jewelery/Clocks",
			"Objects.Dishes/Glass", "Objects.Computers", "Objects.Games/Leisure/Sports", "Objects.Printed Materials",
			"Objects.House", "Objects.Tools/Utensils", "Objects.Music", "Objects.Electronics",
			"Objects.Apparel/Fabrics", "Objects.Mechanics/Optics", "Objects.Electric Materials", "Objects.Contents",
			"Objects.Other", "Transportation.Roads", "Transportation.Aerial Transport", "Transportation.Urban",
			"Transportation.Nautical", "Transportation.Railway", "Transportation.Outer Space", "Transportation.Other",
			"Food & Drink.Drinks", "Food & Drink.Food", "Food & Drink.Dining/Preparation", "Sports & Leisure.Sports",
			"Sports & Leisure.Leisure", "Backgrounds & Textures.Materials", "Backgrounds & Textures.Textures",
			"Backgrounds & Textures.Raw Materials", "Backgrounds & Textures.Backgrounds", "Abstract.Shapes",
			"Abstract.Light/Shade", "Abstract.Movement", "Abstract.Mist", "Abstract.Reflection/Mirror",
			"Abstract.Fire/Flame", "Abstract.Graffiti", "Abstract.Loop/Spring", "Abstract.Smoke",
			"Abstract.Sign/Symbol", "Abstract.Other", "Other.3D Images", "Other.Retro", "Other.Photography Techniques",
			"Other.Calendars", "Other.Frames", "Other.Buttons", "Other.Icons" };

	public static String[] conceptual = new String[] { "Business.Business Concepts", "Business.Business People",
			"Business.Finance/Money", "Business.Business Industries", "Business.Business/Ecology",
			"Business.Business/Commerce", "Business.Business Situations", "Technology.Telecommunications",
			"Technology.Computers", "Technology.Internet", "Technology.Transportation",
			"Emotions & Feelings.Happiness", "Emotions & Feelings.Anger", "Emotions & Feelings.Sadness",
			"Emotions & Feelings.Love", "Emotions & Feelings.Reactions", "Concepts.Relations", "Concepts.Spirit",
			"Concepts.Achievements", "Concepts.Time", "Concepts.Security", "Concepts.Life", "Concepts.Society Values",
			"Concepts.Culture", "Human Features.Strength", "Human Features.Weakness", "Human Features.Positive",
			"Human Features.Negative", "Lifestyles.Family", "Lifestyles.Religion", "Lifestyles.Couples",
			"Lifestyles.Urban Life", "Lifestyles.Old Age", "Lifestyles.Youth", "Lifestyles.Celebrations",
			"Lifestyles.Education", "Leisure.Holiday", "Leisure.Art", "Leisure.Nature", "Leisure.Party",
			"Leisure.Home/Garden", "Leisure.Food", "Leisure.Entertainment", "Welfare.Health", "Welfare.Beauty",
			"Welfare.Sports", "Welfare.Soul", "Science & Nature.Research", "Science & Nature.Applied Sciences",
			"Science & Nature.Esoteric", "Science & Nature.Space", "Science & Nature.Medicine",
			"Science & Nature.Nature", "Social Issues.Addiction", "Social Issues.Criminality",
			"Social Issues.Gender Issues", "Social Issues.Health", "Social Issues.Family", "Social Issues.Poverty",
			"Social Issues.Environment", "Social Issues.Ethics", "Social Issues.Business/Employment",
			"Social Issues.Justice", "Travel.Asian Landmarks", "Travel.Asia", "Travel.European Landmarks",
			"Travel.Europe", "Travel.American Landmarks", "Travel.America", "Travel.Africa", "Travel.Middle East",
			"Travel.Oceania", "Travel.North/South Pole" };

}

/**
"Landscapes.City",
"Landscapes.Village",
"Landscapes.Countryside",
"Landscapes.Mountain",
"Landscapes.Island",
"Landscapes.Desert",
"Landscapes.Water",
"Landscapes.Sky",
"Landscapes.Underwater",
"Landscapes.Natural Landscape",
"Landscapes.Natural Disasters",
"Landscapes.Bird's Eye View",
"Landscapes.Other",
"Architecture.Historical Architecture",
"Architecture.Statues/Creations",
"Architecture.Religious/Sacred",
"Architecture.Modern Building",
"Architecture.Industrial",
"Architecture.Commercial Building ",
"Architecture.Home Renovations",
"Architecture.Public Construction",
"Architecture.Monuments",
"Architecture.Infrastructure",
"Architecture.Other",
"People.In Studio",
"People.On Location",
"People.In Action",
"People.Body Part",
"People.In Uniform",
"Fauna & Flora.Animals",
"Fauna & Flora.Flora",
"Objects.Art",
"Objects.Health/Hygiene",
"Objects.Jewelery/Clocks",
"Objects.Dishes/Glass",
"Objects.Computers",
"Objects.Games/Leisure/Sports",
"Objects.Printed Materials",
"Objects.House",
"Objects.Tools/Utensils",
"Objects.Music",
"Objects.Electronics",
"Objects.Apparel/Fabrics",
"Objects.Mechanics/Optics",
"Objects.Electric Materials",
"Objects.Contents",
"Objects.Other",
"Transportation.Roads",
"Transportation.Aerial Transport",
"Transportation.Urban",
"Transportation.Nautical",
"Transportation.Railway",
"Transportation.Outer Space",
"Transportation.Other",
"Food & Drink.Drinks",
"Food & Drink.Food",
"Food & Drink.Dining/Preparation",
"Sports & Leisure.Sports",
"Sports & Leisure.Leisure",
"Backgrounds & Textures.Materials",
"Backgrounds & Textures.Textures",
"Backgrounds & Textures.Raw Materials",
"Backgrounds & Textures.Backgrounds",
"Abstract.Shapes",
"Abstract.Light/Shade",
"Abstract.Movement",
"Abstract.Mist",
"Abstract.Reflection/Mirror",
"Abstract.Fire/Flame",
"Abstract.Graffiti",
"Abstract.Loop/Spring",
"Abstract.Smoke",
"Abstract.Sign/Symbol",
"Abstract.Other",
"Other.3D Images",
"Other.Retro",
"Other.Photography Techniques",
"Other.Calendars",
"Other.Frames",
"Other.Buttons",
"Other.Icons"
*/
/**
 * "Business.Business Concepts",
"Business.Business People",
"Business.Finance/Money",
"Business.Business Industries",
"Business.Business/Ecology",
"Business.Business/Commerce",
"Business.Business Situations",
"Technology.Telecommunications",
"Technology.Computers",
"Technology.Internet",
"Technology.Transportation",
"Emotions & Feelings.Happiness",
"Emotions & Feelings.Anger",
"Emotions & Feelings.Sadness",
"Emotions & Feelings.Love",
"Emotions & Feelings.Reactions",
"Concepts.Relations",
"Concepts.Spirit",
"Concepts.Achievements",
"Concepts.Time",
"Concepts.Security",
"Concepts.Life",
"Concepts.Society Values",
"Concepts.Culture",
"Human Features.Strength",
"Human Features.Weakness",
"Human Features.Positive",
"Human Features.Negative",
"Lifestyles.Family",
"Lifestyles.Religion",
"Lifestyles.Couples",
"Lifestyles.Urban Life",
"Lifestyles.Old Age",
"Lifestyles.Youth",
"Lifestyles.Celebrations",
"Lifestyles.Education",
"Leisure.Holiday",
"Leisure.Art",
"Leisure.Nature",
"Leisure.Party",
"Leisure.Home/Garden",
"Leisure.Food",
"Leisure.Entertainment",
"Welfare.Health",
"Welfare.Beauty",
"Welfare.Sports",
"Welfare.Soul",
"Science & Nature.Research",
"Science & Nature.Applied Sciences",
"Science & Nature.Esoteric",
"Science & Nature.Space",
"Science & Nature.Medicine",
"Science & Nature.Nature",
"Social Issues.Addiction",
"Social Issues.Criminality",
"Social Issues.Gender Issues",
"Social Issues.Health",
"Social Issues.Family",
"Social Issues.Poverty",
"Social Issues.Environment",
"Social Issues.Ethics",
"Social Issues.Business/Employment",
"Social Issues.Justice",
"Travel.Asian Landmarks",
"Travel.Asia",
"Travel.European Landmarks",
"Travel.Europe",
"Travel.American Landmarks",
"Travel.America",
"Travel.Africa",
"Travel.Middle East",
"Travel.Oceania",
"Travel.North/South Pole"
 */ 
